name: translatron
description: A package for translations, from api calls. Only use if your backend team can provide the needed api urls!
version: 1.1.2
homepage: https://dudasmiklos.com/
repository: https://github.com/DudasMiklos/translatron
documentation: https://dudasmiklos.com/

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

executables:
  translatron: translatron

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  args: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
